### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by vinurk** [blender/docs.blender.org#17]
Hi I am just starting out with open source projects. (This is my first one)
Can i make a dark mode version of the website.

**Comment by venomgfx** [comment]
Do you mean the landing page of docs.blender.org or the manual? 

The manual uses a Sphinx theme IIRC, which I guess must have a dark theme already since it's such a popular theme. Although I'm not familiar with it.

docs.blender.org uses the blender.org `bthree` theme which already has a dark mode (used for code.blender.org). For the landing page of docs.blender.org I'd leave it to match blender.org.
